annotations:
  diskScanAppVersion: 1.1.30
  windowsAppVersion: 1.0.1
apiVersion: v2
appVersion: 1.0.8327
description: Wiz Sensor helm chart
home: https://www.wiz.io/
name: wiz-sensor
type: application
version: 1.0.8401
