apiVersion: v2
appVersion: "2.9"
dependencies:
- name: wiz-common
  repository: https://wiz-sec.github.io/charts
  version: 0.1.9
description: Wiz Broker for tunneling http traffic to Wiz backend
name: wiz-broker
type: application
version: 2.5.1
