{{- $createSecret := include "wiz-sensor.createSecret" . }}
{{- if eq $createSecret "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiz-sensor.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "wiz-sensor.labels" . | nindent 4 }}
  {{- with .Values.wizApiToken.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  clientId: {{ required "A valid clientId value is required! Use --set wizApiToken.clientId=..." .Values.wizApiToken.clientId | quote }}
  clientToken: {{ required "A valid clientToken value is required! Use --set wizApiToken.clientToken=..." .Values.wizApiToken.clientToken | quote }}
  {{- if .Values.wizApiToken.clientEndpoint }}
  clientEndpoint: {{ .Values.wizApiToken.clientEndpoint | quote }}
  {{- end }}
{{- end -}}