apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-app
  namespace: sample-app
spec:
  rules:
  - host: sample-app-staging.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sample-app
            port:
              number: 80
  tls:
  - hosts:
    - sample-app-staging.example.com
    secretName: sample-app-staging-tls
