apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - nginx-ingress.yaml
  - wiz-helm-repository.yaml
  - wiz-sensor-namespace.yaml
  - wiz-sensor-helmrelease.yaml
